version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: acq-rpn-client
    volumes:
      - ./client:/app 
      - /app/node_modules 
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: acq-rpn-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - '5010:5010'
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - PORT=5010
    restart: unless-stopped

  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: acq-rpn-nginx
  #   depends_on:
  #     - client
  #     - server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./client/dist:/usr/share/nginx/html:ro
  #   restart: unless-stopped